spring.application.name=reservationsystem

spring.datasource.url=${DATABASE_URL}${DB_NAME}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

server.servlet.context-path=/api/vs1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secretKey=$(railway_secret_key)
